// To parse this JSON data, do
//
//     final userDetails = userDetailsFromJson(jsonString);

import 'dart:convert';

UserDetails userDetailsFromJson(String str) => UserDetails.fromJson(json.decode(str));

String userDetailsToJson(UserDetails data) => json.encode(data.toJson());

class UserDetails {
    dynamic admissionCategory;
    dynamic bankAccountNo;
    dynamic bankBranch;
    dynamic categoryRank;
    String comptitionExamName;
    dynamic counselingFee;
    dynamic diplomaBranch;
    dynamic diplomaCgpa;
    dynamic diplomaInstitute;
    dynamic diplomaMarkObtained;
    dynamic diplomaMedium;
    dynamic diplomaPercentage;
    dynamic diplomaRollNumber;
    dynamic diplomaTotalMark;
    dynamic diplomaUniversity;
    dynamic diplomaYearOfPassing;
    dynamic fatherAnnualIncome;
    dynamic fatherEducation;
    dynamic graduationCgpa;
    dynamic graduationDegree;
    dynamic graduationInstitute;
    dynamic graduationMarks;
    dynamic graduationMedium;
    dynamic graduationPercentage;
    dynamic graduationRollNumber;
    dynamic graduationTotalMarks;
    dynamic graduationUniversity;
    dynamic graduationYear;
    dynamic guardianAddress;
    dynamic guardianCity;
    dynamic guardianEmailId;
    dynamic guardianMobileNumber;
    dynamic guardianName;
    dynamic guardianPinCode;
    dynamic guardianRelationship;
    dynamic guardianState;
    int hostelTaken;
    dynamic iFscCode;
    String jeeRank;
    String jeeRollNumber;
    dynamic jeeScore;
    dynamic jeeStateRank;
    dynamic mcaMathMaxMarks;
    dynamic mcaMathPercentage;
    dynamic mcaMathScoredMarks;
    dynamic minority;
    dynamic motherAnnualIncome;
    dynamic motherEducation;
    dynamic nameOfBank;
    dynamic permenentAddress;
    dynamic permenentCity;
    dynamic permenentDistrict;
    dynamic permenentPincode;
    dynamic permenentState;
    String presentCity;
    String presentDistrict;
    String presentPincode;
    String presentState;
    int scholarship;
    int secondYearLateralEntry;
    dynamic stateofDomicile;
    int supernumerarySeat;
    dynamic tenthCgpa;
    String tenthClassPercentage;
    dynamic tenthMarksObtained;
    String tenthPassingyear;
    dynamic tenthRollNumber;
    dynamic tenthSchoolMedium;
    dynamic tenthSchoolName;
    dynamic tenthTotalMarks;
    dynamic tenthboardDetail;
    String tenthboardName;
    String title;
    int transportTaken;
    dynamic twelfthAnyOtherMaxMark;
    dynamic twelfthAnyOtherPercentage;
    dynamic twelfthAnyOtherScoredMark;
    dynamic twelfthBoardDetail;
    dynamic twelfthBoardMedium;
    dynamic twelfthCgpa;
    String twelfthChemistryMaxMark;
    int twelfthChemistryPercentage;
    String twelfthChemistryScoredMark;
    dynamic twelfthComputerMaxMark;
    dynamic twelfthComputerPercentage;
    dynamic twelfthComputerScoredMark;
    dynamic twelfthEnglishMaxMark;
    dynamic twelfthEnglishPercentage;
    dynamic twelfthEnglishScoredMark;
    dynamic twelfthInstitute;
    dynamic twelfthMarksObtained;
    String twelfthMathMaxMark;
    int twelfthMathPercentage;
    String twelfthMathScoredMark;
    dynamic twelfthPcmMaxMark;
    dynamic twelfthPcmPercentage;
    String twelfthPcmScoredMark;
    String twelfthPhysicMaxMark;
    int twelfthPhysicPercentage;
    String twelfthPhysicScoredMark;
    dynamic twelfthRollNumber;
    dynamic twelfthTotalMarks;
    String twelfthboardName;
    String twelfthpassingYear;
    String twelthClassPercentage;
    dynamic upseGeneralRank;
    dynamic voterCardNumber;
    String mothersMobileNumber;
    String parentMobileNumber;
    dynamic admissionFormNumber;
    int batchId;
    dynamic dateOfAdmission;
    DateTime admissionDate;
    DateTime dob;
    int categoryId;
    dynamic lastSchoolStudied;
    int branchId;
    String admissionNumber;
    String aadhaarNumber;
    int courseId;
    String activeSubStatus;
    String activeStatus;
    String modeOfAdmission;
    String isEws;
    String isTfw;
    int subModeAdmission;
    String fatherName;
    String parentFullName;
    String motherName;
    String motherFullName;
    String gender;
    String firstName;
    String middleName;
    String lastName;
    String email;
    String addressLine1;
    String address;
    String nation;
    String caste;
    String religion;
    String rollNumber;
    String smsMobileNumber;
    String parentOccupation;
    String motherbusiness;
    String perobtained;
    String parentIncome;
    String parentPhone;
    String phone;
    String userDetailsReligion;
    String bpl;
    String selectedBatch;
    String selectedCourse;
    String selectedBranch;
    String selectedSemester;

    UserDetails({
        required this.admissionCategory,
        required this.bankAccountNo,
        required this.bankBranch,
        required this.categoryRank,
        required this.comptitionExamName,
        required this.counselingFee,
        required this.diplomaBranch,
        required this.diplomaCgpa,
        required this.diplomaInstitute,
        required this.diplomaMarkObtained,
        required this.diplomaMedium,
        required this.diplomaPercentage,
        required this.diplomaRollNumber,
        required this.diplomaTotalMark,
        required this.diplomaUniversity,
        required this.diplomaYearOfPassing,
        required this.fatherAnnualIncome,
        required this.fatherEducation,
        required this.graduationCgpa,
        required this.graduationDegree,
        required this.graduationInstitute,
        required this.graduationMarks,
        required this.graduationMedium,
        required this.graduationPercentage,
        required this.graduationRollNumber,
        required this.graduationTotalMarks,
        required this.graduationUniversity,
        required this.graduationYear,
        required this.guardianAddress,
        required this.guardianCity,
        required this.guardianEmailId,
        required this.guardianMobileNumber,
        required this.guardianName,
        required this.guardianPinCode,
        required this.guardianRelationship,
        required this.guardianState,
        required this.hostelTaken,
        required this.iFscCode,
        required this.jeeRank,
        required this.jeeRollNumber,
        required this.jeeScore,
        required this.jeeStateRank,
        required this.mcaMathMaxMarks,
        required this.mcaMathPercentage,
        required this.mcaMathScoredMarks,
        required this.minority,
        required this.motherAnnualIncome,
        required this.motherEducation,
        required this.nameOfBank,
        required this.permenentAddress,
        required this.permenentCity,
        required this.permenentDistrict,
        required this.permenentPincode,
        required this.permenentState,
        required this.presentCity,
        required this.presentDistrict,
        required this.presentPincode,
        required this.presentState,
        required this.scholarship,
        required this.secondYearLateralEntry,
        required this.stateofDomicile,
        required this.supernumerarySeat,
        required this.tenthCgpa,
        required this.tenthClassPercentage,
        required this.tenthMarksObtained,
        required this.tenthPassingyear,
        required this.tenthRollNumber,
        required this.tenthSchoolMedium,
        required this.tenthSchoolName,
        required this.tenthTotalMarks,
        required this.tenthboardDetail,
        required this.tenthboardName,
        required this.title,
        required this.transportTaken,
        required this.twelfthAnyOtherMaxMark,
        required this.twelfthAnyOtherPercentage,
        required this.twelfthAnyOtherScoredMark,
        required this.twelfthBoardDetail,
        required this.twelfthBoardMedium,
        required this.twelfthCgpa,
        required this.twelfthChemistryMaxMark,
        required this.twelfthChemistryPercentage,
        required this.twelfthChemistryScoredMark,
        required this.twelfthComputerMaxMark,
        required this.twelfthComputerPercentage,
        required this.twelfthComputerScoredMark,
        required this.twelfthEnglishMaxMark,
        required this.twelfthEnglishPercentage,
        required this.twelfthEnglishScoredMark,
        required this.twelfthInstitute,
        required this.twelfthMarksObtained,
        required this.twelfthMathMaxMark,
        required this.twelfthMathPercentage,
        required this.twelfthMathScoredMark,
        required this.twelfthPcmMaxMark,
        required this.twelfthPcmPercentage,
        required this.twelfthPcmScoredMark,
        required this.twelfthPhysicMaxMark,
        required this.twelfthPhysicPercentage,
        required this.twelfthPhysicScoredMark,
        required this.twelfthRollNumber,
        required this.twelfthTotalMarks,
        required this.twelfthboardName,
        required this.twelfthpassingYear,
        required this.twelthClassPercentage,
        required this.upseGeneralRank,
        required this.voterCardNumber,
        required this.mothersMobileNumber,
        required this.parentMobileNumber,
        required this.admissionFormNumber,
        required this.batchId,
        required this.dateOfAdmission,
        required this.admissionDate,
        required this.dob,
        required this.categoryId,
        required this.lastSchoolStudied,
        required this.branchId,
        required this.admissionNumber,
        required this.aadhaarNumber,
        required this.courseId,
        required this.activeSubStatus,
        required this.activeStatus,
        required this.modeOfAdmission,
        required this.isEws,
        required this.isTfw,
        required this.subModeAdmission,
        required this.fatherName,
        required this.parentFullName,
        required this.motherName,
        required this.motherFullName,
        required this.gender,
        required this.firstName,
        required this.middleName,
        required this.lastName,
        required this.email,
        required this.addressLine1,
        required this.address,
        required this.nation,
        required this.caste,
        required this.religion,
        required this.rollNumber,
        required this.smsMobileNumber,
        required this.parentOccupation,
        required this.motherbusiness,
        required this.perobtained,
        required this.parentIncome,
        required this.parentPhone,
        required this.phone,
        required this.userDetailsReligion,
        required this.bpl,
        required this.selectedBatch,
        required this.selectedCourse,
        required this.selectedBranch,
        required this.selectedSemester,
    });

    factory UserDetails.fromJson(Map<String, dynamic> json) => UserDetails(
        admissionCategory: json["admissionCategory"],
        bankAccountNo: json["bankAccountNo"],
        bankBranch: json["bankBranch"],
        categoryRank: json["categoryRank"],
        comptitionExamName: json["comptitionExamName"],
        counselingFee: json["counselingFee"],
        diplomaBranch: json["diplomaBranch"],
        diplomaCgpa: json["diplomaCgpa"],
        diplomaInstitute: json["diplomaInstitute"],
        diplomaMarkObtained: json["diplomaMarkObtained"],
        diplomaMedium: json["diplomaMedium"],
        diplomaPercentage: json["diplomaPercentage"],
        diplomaRollNumber: json["diplomaRollNumber"],
        diplomaTotalMark: json["diplomaTotalMark"],
        diplomaUniversity: json["diplomaUniversity"],
        diplomaYearOfPassing: json["diplomaYearOfPassing"],
        fatherAnnualIncome: json["fatherAnnualIncome"],
        fatherEducation: json["fatherEducation"],
        graduationCgpa: json["graduationCgpa"],
        graduationDegree: json["graduationDegree"],
        graduationInstitute: json["graduationInstitute"],
        graduationMarks: json["graduationMarks"],
        graduationMedium: json["graduationMedium"],
        graduationPercentage: json["graduationPercentage"],
        graduationRollNumber: json["graduationRollNumber"],
        graduationTotalMarks: json["graduationTotalMarks"],
        graduationUniversity: json["graduationUniversity"],
        graduationYear: json["graduationYear"],
        guardianAddress: json["guardianAddress"],
        guardianCity: json["guardianCity"],
        guardianEmailId: json["guardianEmailId"],
        guardianMobileNumber: json["guardianMobileNumber"],
        guardianName: json["guardianName"],
        guardianPinCode: json["guardianPinCode"],
        guardianRelationship: json["guardianRelationship"],
        guardianState: json["guardianState"],
        hostelTaken: json["hostelTaken"],
        iFscCode: json["iFSCCode"],
        jeeRank: json["jeeRank"],
        jeeRollNumber: json["jeeRollNumber"],
        jeeScore: json["jeeScore"],
        jeeStateRank: json["jeeStateRank"],
        mcaMathMaxMarks: json["mcaMathMaxMarks"],
        mcaMathPercentage: json["mcaMathPercentage"],
        mcaMathScoredMarks: json["mcaMathScoredMarks"],
        minority: json["minority"],
        motherAnnualIncome: json["motherAnnualIncome"],
        motherEducation: json["motherEducation"],
        nameOfBank: json["nameOfBank"],
        permenentAddress: json["permenentAddress"],
        permenentCity: json["permenentCity"],
        permenentDistrict: json["permenentDistrict"],
        permenentPincode: json["permenentPincode"],
        permenentState: json["permenentState"],
        presentCity: json["presentCity"],
        presentDistrict: json["presentDistrict"],
        presentPincode: json["presentPincode"],
        presentState: json["presentState"],
        scholarship: json["scholarship"],
        secondYearLateralEntry: json["secondYearLateralEntry"],
        stateofDomicile: json["stateofDomicile"],
        supernumerarySeat: json["supernumerarySeat"],
        tenthCgpa: json["tenthCgpa"],
        tenthClassPercentage: json["tenthClassPercentage"],
        tenthMarksObtained: json["tenthMarksObtained"],
        tenthPassingyear: json["tenthPassingyear"],
        tenthRollNumber: json["tenthRollNumber"],
        tenthSchoolMedium: json["tenthSchoolMedium"],
        tenthSchoolName: json["tenthSchoolName"],
        tenthTotalMarks: json["tenthTotalMarks"],
        tenthboardDetail: json["tenthboardDetail"],
        tenthboardName: json["tenthboardName"],
        title: json["title"],
        transportTaken: json["transportTaken"],
        twelfthAnyOtherMaxMark: json["twelfthAnyOtherMaxMark"],
        twelfthAnyOtherPercentage: json["twelfthAnyOtherPercentage"],
        twelfthAnyOtherScoredMark: json["twelfthAnyOtherScoredMark"],
        twelfthBoardDetail: json["twelfthBoardDetail"],
        twelfthBoardMedium: json["twelfthBoardMedium"],
        twelfthCgpa: json["twelfthCgpa"],
        twelfthChemistryMaxMark: json["twelfthChemistryMaxMark"],
        twelfthChemistryPercentage: json["twelfthChemistryPercentage"],
        twelfthChemistryScoredMark: json["twelfthChemistryScoredMark"],
        twelfthComputerMaxMark: json["twelfthComputerMaxMark"],
        twelfthComputerPercentage: json["twelfthComputerPercentage"],
        twelfthComputerScoredMark: json["twelfthComputerScoredMark"],
        twelfthEnglishMaxMark: json["twelfthEnglishMaxMark"],
        twelfthEnglishPercentage: json["twelfthEnglishPercentage"],
        twelfthEnglishScoredMark: json["twelfthEnglishScoredMark"],
        twelfthInstitute: json["twelfthInstitute"],
        twelfthMarksObtained: json["twelfthMarksObtained"],
        twelfthMathMaxMark: json["twelfthMathMaxMark"],
        twelfthMathPercentage: json["twelfthMathPercentage"],
        twelfthMathScoredMark: json["twelfthMathScoredMark"],
        twelfthPcmMaxMark: json["twelfthPcmMaxMark"],
        twelfthPcmPercentage: json["twelfthPcmPercentage"],
        twelfthPcmScoredMark: json["twelfthPcmScoredMark"],
        twelfthPhysicMaxMark: json["twelfthPhysicMaxMark"],
        twelfthPhysicPercentage: json["twelfthPhysicPercentage"],
        twelfthPhysicScoredMark: json["twelfthPhysicScoredMark"],
        twelfthRollNumber: json["twelfthRollNumber"],
        twelfthTotalMarks: json["twelfthTotalMarks"],
        twelfthboardName: json["twelfthboardName"],
        twelfthpassingYear: json["twelfthpassingYear"],
        twelthClassPercentage: json["twelthClassPercentage"],
        upseGeneralRank: json["upseGeneralRank"],
        voterCardNumber: json["voterCardNumber"],
        mothersMobileNumber: json["mothersMobileNumber"],
        parentMobileNumber: json["parentMobileNumber"],
        admissionFormNumber: json["admissionFormNumber"],
        batchId: json["batchId"],
        dateOfAdmission: json["dateOfAdmission"],
        admissionDate: DateTime.parse(json["admissionDate"]),
        dob: DateTime.parse(json["dob"]),
        categoryId: json["categoryId"],
        lastSchoolStudied: json["lastSchoolStudied"],
        branchId: json["branchId"],
        admissionNumber: json["admissionNumber"],
        aadhaarNumber: json["aadhaarNumber"],
        courseId: json["courseId"],
        activeSubStatus: json["activeSubStatus"],
        activeStatus: json["activeStatus"],
        modeOfAdmission: json["modeOfAdmission"],
        isEws: json["isEWS"],
        isTfw: json["isTFW"],
        subModeAdmission: json["subModeAdmission"],
        fatherName: json["fatherName"],
        parentFullName: json["parentFullName"],
        motherName: json["motherName"],
        motherFullName: json["motherFullName"],
        gender: json["gender"],
        firstName: json["firstName"],
        middleName: json["middleName"],
        lastName: json["lastName"],
        email: json["email"],
        addressLine1: json["addressLine1"],
        address: json["address"],
        nation: json["nation"],
        caste: json["caste"],
        religion: json["Religion"],
        rollNumber: json["rollNumber"],
        smsMobileNumber: json["smsMobileNumber"],
        parentOccupation: json["parentOccupation"],
        motherbusiness: json["motherbusiness"],
        perobtained: json["perobtained"],
        parentIncome: json["parentIncome"],
        parentPhone: json["parentPhone"],
        phone: json["phone"],
        userDetailsReligion: json["religion"],
        bpl: json["bpl"],
        selectedBatch: json["selectedBatch"],
        selectedCourse: json["selectedCourse"],
        selectedBranch: json["selectedBranch"],
        selectedSemester: json["selectedSemester"],
    );

    Map<String, dynamic> toJson() => {
        "admissionCategory": admissionCategory,
        "bankAccountNo": bankAccountNo,
        "bankBranch": bankBranch,
        "categoryRank": categoryRank,
        "comptitionExamName": comptitionExamName,
        "counselingFee": counselingFee,
        "diplomaBranch": diplomaBranch,
        "diplomaCgpa": diplomaCgpa,
        "diplomaInstitute": diplomaInstitute,
        "diplomaMarkObtained": diplomaMarkObtained,
        "diplomaMedium": diplomaMedium,
        "diplomaPercentage": diplomaPercentage,
        "diplomaRollNumber": diplomaRollNumber,
        "diplomaTotalMark": diplomaTotalMark,
        "diplomaUniversity": diplomaUniversity,
        "diplomaYearOfPassing": diplomaYearOfPassing,
        "fatherAnnualIncome": fatherAnnualIncome,
        "fatherEducation": fatherEducation,
        "graduationCgpa": graduationCgpa,
        "graduationDegree": graduationDegree,
        "graduationInstitute": graduationInstitute,
        "graduationMarks": graduationMarks,
        "graduationMedium": graduationMedium,
        "graduationPercentage": graduationPercentage,
        "graduationRollNumber": graduationRollNumber,
        "graduationTotalMarks": graduationTotalMarks,
        "graduationUniversity": graduationUniversity,
        "graduationYear": graduationYear,
        "guardianAddress": guardianAddress,
        "guardianCity": guardianCity,
        "guardianEmailId": guardianEmailId,
        "guardianMobileNumber": guardianMobileNumber,
        "guardianName": guardianName,
        "guardianPinCode": guardianPinCode,
        "guardianRelationship": guardianRelationship,
        "guardianState": guardianState,
        "hostelTaken": hostelTaken,
        "iFSCCode": iFscCode,
        "jeeRank": jeeRank,
        "jeeRollNumber": jeeRollNumber,
        "jeeScore": jeeScore,
        "jeeStateRank": jeeStateRank,
        "mcaMathMaxMarks": mcaMathMaxMarks,
        "mcaMathPercentage": mcaMathPercentage,
        "mcaMathScoredMarks": mcaMathScoredMarks,
        "minority": minority,
        "motherAnnualIncome": motherAnnualIncome,
        "motherEducation": motherEducation,
        "nameOfBank": nameOfBank,
        "permenentAddress": permenentAddress,
        "permenentCity": permenentCity,
        "permenentDistrict": permenentDistrict,
        "permenentPincode": permenentPincode,
        "permenentState": permenentState,
        "presentCity": presentCity,
        "presentDistrict": presentDistrict,
        "presentPincode": presentPincode,
        "presentState": presentState,
        "scholarship": scholarship,
        "secondYearLateralEntry": secondYearLateralEntry,
        "stateofDomicile": stateofDomicile,
        "supernumerarySeat": supernumerarySeat,
        "tenthCgpa": tenthCgpa,
        "tenthClassPercentage": tenthClassPercentage,
        "tenthMarksObtained": tenthMarksObtained,
        "tenthPassingyear": tenthPassingyear,
        "tenthRollNumber": tenthRollNumber,
        "tenthSchoolMedium": tenthSchoolMedium,
        "tenthSchoolName": tenthSchoolName,
        "tenthTotalMarks": tenthTotalMarks,
        "tenthboardDetail": tenthboardDetail,
        "tenthboardName": tenthboardName,
        "title": title,
        "transportTaken": transportTaken,
        "twelfthAnyOtherMaxMark": twelfthAnyOtherMaxMark,
        "twelfthAnyOtherPercentage": twelfthAnyOtherPercentage,
        "twelfthAnyOtherScoredMark": twelfthAnyOtherScoredMark,
        "twelfthBoardDetail": twelfthBoardDetail,
        "twelfthBoardMedium": twelfthBoardMedium,
        "twelfthCgpa": twelfthCgpa,
        "twelfthChemistryMaxMark": twelfthChemistryMaxMark,
        "twelfthChemistryPercentage": twelfthChemistryPercentage,
        "twelfthChemistryScoredMark": twelfthChemistryScoredMark,
        "twelfthComputerMaxMark": twelfthComputerMaxMark,
        "twelfthComputerPercentage": twelfthComputerPercentage,
        "twelfthComputerScoredMark": twelfthComputerScoredMark,
        "twelfthEnglishMaxMark": twelfthEnglishMaxMark,
        "twelfthEnglishPercentage": twelfthEnglishPercentage,
        "twelfthEnglishScoredMark": twelfthEnglishScoredMark,
        "twelfthInstitute": twelfthInstitute,
        "twelfthMarksObtained": twelfthMarksObtained,
        "twelfthMathMaxMark": twelfthMathMaxMark,
        "twelfthMathPercentage": twelfthMathPercentage,
        "twelfthMathScoredMark": twelfthMathScoredMark,
        "twelfthPcmMaxMark": twelfthPcmMaxMark,
        "twelfthPcmPercentage": twelfthPcmPercentage,
        "twelfthPcmScoredMark": twelfthPcmScoredMark,
        "twelfthPhysicMaxMark": twelfthPhysicMaxMark,
        "twelfthPhysicPercentage": twelfthPhysicPercentage,
        "twelfthPhysicScoredMark": twelfthPhysicScoredMark,
        "twelfthRollNumber": twelfthRollNumber,
        "twelfthTotalMarks": twelfthTotalMarks,
        "twelfthboardName": twelfthboardName,
        "twelfthpassingYear": twelfthpassingYear,
        "twelthClassPercentage": twelthClassPercentage,
        "upseGeneralRank": upseGeneralRank,
        "voterCardNumber": voterCardNumber,
        "mothersMobileNumber": mothersMobileNumber,
        "parentMobileNumber": parentMobileNumber,
        "admissionFormNumber": admissionFormNumber,
        "batchId": batchId,
        "dateOfAdmission": dateOfAdmission,
        "admissionDate": "${admissionDate.year.toString().padLeft(4, '0')}-${admissionDate.month.toString().padLeft(2, '0')}-${admissionDate.day.toString().padLeft(2, '0')}",
        "dob": "${dob.year.toString().padLeft(4, '0')}-${dob.month.toString().padLeft(2, '0')}-${dob.day.toString().padLeft(2, '0')}",
        "categoryId": categoryId,
        "lastSchoolStudied": lastSchoolStudied,
        "branchId": branchId,
        "admissionNumber": admissionNumber,
        "aadhaarNumber": aadhaarNumber,
        "courseId": courseId,
        "activeSubStatus": activeSubStatus,
        "activeStatus": activeStatus,
        "modeOfAdmission": modeOfAdmission,
        "isEWS": isEws,
        "isTFW": isTfw,
        "subModeAdmission": subModeAdmission,
        "fatherName": fatherName,
        "parentFullName": parentFullName,
        "motherName": motherName,
        "motherFullName": motherFullName,
        "gender": gender,
        "firstName": firstName,
        "middleName": middleName,
        "lastName": lastName,
        "email": email,
        "addressLine1": addressLine1,
        "address": address,
        "nation": nation,
        "caste": caste,
        "Religion": religion,
        "rollNumber": rollNumber,
        "smsMobileNumber": smsMobileNumber,
        "parentOccupation": parentOccupation,
        "motherbusiness": motherbusiness,
        "perobtained": perobtained,
        "parentIncome": parentIncome,
        "parentPhone": parentPhone,
        "phone": phone,
        "religion": userDetailsReligion,
        "bpl": bpl,
        "selectedBatch": selectedBatch,
        "selectedCourse": selectedCourse,
        "selectedBranch": selectedBranch,
        "selectedSemester": selectedSemester,
    };
}
